"use strict";
exports.__esModule = true;
var Circle_1 = require("./Circle");
var Cylinder_1 = require("./Cylinder");
var circle = new Circle_1.Circle(15, "red");
var cylinder = new Cylinder_1.Cylinder(20, "blue", 50);
console.log(circle);
console.log(circle.getArea());
console.log(cylinder);
console.log(cylinder.getVolume());
console.log(cylinder.getArea());
